'use client';

import React, { useRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Printer, Download, FileJson } from 'lucide-react';
import api from '@/lib/api';
import { toast } from 'sonner';

interface FinancialReportLayoutProps {
    title: string;
    period: string;
    companyName?: string;
    companyAddress?: string;
    children: React.ReactNode;
    type: 'Balance Sheet' | 'Income Statement' | 'Cash Flow';
}

export function FinancialReportLayout({
    title,
    period,
    companyName = "PT. MAVLANA FINTECH INDONESIA",
    companyAddress = "Menara Standard Chartered Lt. 30, Jl. Prof. Dr. Satrio No. 164, Jakarta Selatan",
    children,
    type
}: FinancialReportLayoutProps) {
    const componentRef = useRef<HTMLDivElement>(null);

    const handlePrint = useReactToPrint({
        contentRef: componentRef,
        documentTitle: `Laporan-${title}-${period}`,
    });

    // Note: React-to-print is client side printing. 
    // Backend PDF export can be called for "Official" download.

    const handleExport = async (format: 'pdf' | 'excel') => {
        try {
            const res = await api.post('/reports/export', { type, format }, { responseType: 'blob' });

            // Create blob link to download
            const url = window.URL.createObjectURL(new Blob([res.data]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', `${title}-Report.${format === 'excel' ? 'xlsx' : 'pdf'}`);
            document.body.appendChild(link);
            link.click();
            link.remove();
        } catch (error) {
            toast.error('Gagal mengunduh dokumen.');
        }
    };

    return (
        <div className="space-y-4">
            <div className="flex justify-end space-x-2 print:hidden">
                <Button variant="outline" size="sm" onClick={handlePrint}><Printer className="mr-2 h-4 w-4 " /> Print / PDF</Button>
                <Button variant="outline" size="sm" onClick={() => handleExport('excel')}><FileJson className="mr-2 h-4 w-4" /> Excel</Button>
            </div>

            <div className="border border-slate-200 shadow-sm bg-white min-h-[800px] p-10 print:p-0 print:border-0 print:shadow-none" ref={componentRef}>
                {/* Letterhead */}
                <div className="mb-8 border-b-2 border-slate-800 pb-4">
                    <h1 className="text-2xl font-bold uppercase tracking-wider text-slate-900">{companyName}</h1>
                    <p className="text-sm text-slate-500">{companyAddress}</p>
                </div>

                {/* Report Header */}
                <div className="text-center mb-8">
                    <h2 className="text-xl font-bold uppercase text-slate-800">{title}</h2>
                    <p className="text-muted-foreground">Periode: {period}</p>
                </div>

                {/* Content */}
                <div className="report-content">
                    {children}
                </div>

                {/* Footer / Signatures */}
                <div className="mt-16 pt-8 border-t flex justify-between text-center break-inside-avoid">
                    <div className="space-y-16">
                        <p className="text-sm font-medium">Dibuat Oleh,</p>
                        <p className="border-t border-slate-400 pt-1 w-40 mx-auto text-sm text-slate-600">( Staff Akuntansi )</p>
                    </div>
                    <div className="space-y-16">
                        <p className="text-sm font-medium">Diperiksa Oleh,</p>
                        <p className="border-t border-slate-400 pt-1 w-40 mx-auto text-sm text-slate-600">( Manajer Keuangan )</p>
                    </div>
                    <div className="space-y-16">
                        <p className="text-sm font-medium">Disetujui Oleh,</p>
                        <p className="border-t border-slate-400 pt-1 w-40 mx-auto text-sm text-slate-600">( Direktur Utama )</p>
                    </div>
                </div>

                <div className="mt-8 text-center text-xs text-slate-300 print:fixed print:bottom-4 print:left-0 print:w-full">
                    Generated by MAVLANA ERP System &bull; {new Date().toLocaleString('id-ID')}
                </div>
            </div>
        </div>
    );
}
